/**
 * Legal placements — what scene 3 offers when you tap an exposed edge.
 *
 * ## Local matching, deliberately
 *
 * Moves are found by **local matching**: butt a hat against an exposed edge in
 * every orientation, keep the ones that don't overlap. They are *not* read off
 * the substitution.
 *
 * That distinction is the whole point of the scene. Local matching admits
 * placements that are legal right now but cannot extend to a full tiling — the
 * traps. Reading moves off the substitution would only ever offer moves that
 * work, and the reader could never fail, so there would be nothing to discover.
 * **The failure has to be reachable.**
 *
 * ## Completeness
 *
 * Candidates are generated by aligning one unit step of the hat's outline
 * against one unit step of the board's frontier. Both are subdivided to single
 * lattice steps first (`boundarySteps`), because the hat's √3 and length-2 edges
 * can span more of the frontier than one merged edge — matching whole edges
 * would silently drop legal moves.
 *
 * Any placement touching the board along an edge shares at least one such step,
 * so this enumeration is complete for edge-adjacent moves. Placements touching
 * only at a single point are excluded, which is what we want: they leave a gap
 * no tile can fill and are not moves a reader should be offered.
 *
 * ## Why candidates are filtered to one kite grid
 *
 * Butting a hat against an exposed edge can land it on a *different* coset of
 * the hexagon sublattice (observed: coset 7 against a board on coset 4). The hat
 * is a polykite and its tilings are polykite tilings on a single grid, so such a
 * placement can never belong to one. It is not an instructive trap, just wrong,
 * so it is dropped.
 *
 * (An attempt to sidestep this with a universally-aligned triangle
 * decomposition failed for a good reason: the hat's √3 edges are the *long*
 * diagonals of lattice rhombi and cut triangles in half, so the hat is not a
 * union of lattice triangles at all. Kites really are the hat's natural cell.)
 */

import { type Eis, add, conj, equals, negate, rot60k, sub } from './eisenstein.js';
import { type Isometry, isoKey, isometry } from './isometry.js';
import { boundaryLoops, boundarySteps, signedArea2, type BoundaryStep } from './hull.js';
import { KiteIndex, hexCoset } from './kites.js';
import { HAT_VERTICES, type Tile } from './patch.js';

/** The 12 linear parts of the hexagonal symmetry group. */
const LINEAR: readonly { rot: number; reflected: boolean }[] = Array.from(
  { length: 12 },
  (_, i) => ({ rot: i % 6, reflected: i >= 6 }),
);

function linear(p: Eis, rot: number, reflected: boolean): Eis {
  return rot60k(reflected ? conj(p) : p, rot);
}

function gcd(a: number, b: number): number {
  a = Math.abs(a);
  b = Math.abs(b);
  while (b) [a, b] = [b, a % b];
  return a || 1;
}

/** The hat's outline as single lattice steps: each step's start and vector. */
const HAT_STEPS: readonly { from: Eis; vec: Eis }[] = (() => {
  const steps: { from: Eis; vec: Eis }[] = [];
  const n = HAT_VERTICES.length;
  for (let i = 0; i < n; i++) {
    const p = HAT_VERTICES[i]!;
    const q = HAT_VERTICES[(i + 1) % n]!;
    const da = q.a - p.a;
    const db = q.b - p.b;
    const count = gcd(da, db);
    const sa = da / count;
    const sb = db / count;
    for (let k = 0; k < count; k++) {
      steps.push({
        from: { a: p.a + sa * k, b: p.b + sb * k },
        vec: { a: sa, b: sb },
      });
    }
  }
  return steps;
})();

/** The board: placed tiles plus their occupancy index. */
export interface Board {
  readonly tiles: readonly Tile[];
  readonly index: KiteIndex;
  /** The kite grid the board sits on; candidates must agree. */
  readonly coset: number;
}

export function makeBoard(tiles: readonly Tile[]): Board {
  if (!tiles.length) throw new Error('a board needs at least one tile');
  return {
    tiles,
    index: new KiteIndex(tiles),
    coset: hexCoset(tiles[0]!.iso),
  };
}

/** The board's exposed frontier, as single counter-clockwise lattice steps. */
export function frontier(board: Board): BoundaryStep[] {
  return boundarySteps(board.tiles);
}

/**
 * Every legal placement that would sit against `step`.
 *
 * The frontier runs counter-clockwise with occupied area on the left, so a tile
 * placed in the free space traverses the same segment the other way — its own
 * edge vector is `from − to`.
 */
export function movesAlongStep(board: Board, step: BoundaryStep): Isometry[] {
  const target = sub(step.from, step.to);
  const out: Isometry[] = [];
  const seen = new Set<string>();

  for (const { rot, reflected } of LINEAR) {
    for (const hatStep of HAT_STEPS) {
      // A reflected placement is wound clockwise, so its counter-clockwise
      // traversal is the reversed vertex order: each edge runs backwards, from
      // the step's far end. Getting this wrong silently produces zero reflected
      // moves — and hat tilings are impossible without reflections.
      const mapped = linear(hatStep.vec, rot, reflected);
      const outward = reflected ? negate(mapped) : mapped;
      if (!equals(outward, target)) continue;

      const anchor = reflected ? add(hatStep.from, hatStep.vec) : hatStep.from;
      const t = sub(step.to, linear(anchor, rot, reflected));
      const iso = isometry(rot, reflected, t);
      const k = isoKey(iso);
      if (seen.has(k)) continue;
      seen.add(k);
      // Edge-matching alone can land a hat on a different kite grid. The hat is
      // a polykite and its tilings are polykite tilings, so such a placement
      // could never belong to one — it is not a trap, just wrong. Drop it.
      if (hexCoset(iso) !== board.coset) continue;
      if (board.index.isFree(iso)) out.push(iso);
    }
  }
  return out;
}

/** Every legal placement anywhere on the frontier, deduplicated. */
export function legalMoves(board: Board): Isometry[] {
  const seen = new Set<string>();
  const out: Isometry[] = [];
  for (const step of frontier(board)) {
    for (const iso of movesAlongStep(board, step)) {
      const k = isoKey(iso);
      if (seen.has(k)) continue;
      seen.add(k);
      out.push(iso);
    }
  }
  return out;
}

/**
 * Play greedily, choosing with `pick`, until the board traps itself or `limit`
 * placements are made.
 *
 * `trapped` means an unfillable pocket has formed. `stalled` means no legal move
 * exists at all, which on an open board essentially never happens — see
 * `holes`.
 */
export function greedyWalk(
  board: Board,
  pick: (moves: readonly Isometry[], step: number) => Isometry,
  limit = 200,
): { placed: Isometry[]; stalled: boolean; trapped: Eis[][] } {
  const tiles = [...board.tiles];
  const index = new KiteIndex(tiles);
  const placed: Isometry[] = [];

  for (let i = 0; i < limit; i++) {
    const current: Board = { tiles, index, coset: board.coset };
    const moves = legalMoves(current);
    if (!moves.length) return { placed, stalled: true, trapped: deadHoles(current) };
    const chosen = pick(moves, i);
    index.add(chosen);
    tiles.push({ kind: 'H', iso: chosen, path: ['H'], trail: [0] });
    placed.push(chosen);

    const next: Board = { tiles, index, coset: board.coset };
    const dead = deadHoles(next);
    if (dead.length) return { placed, stalled: false, trapped: dead };
  }
  return { placed, stalled: false, trapped: [] };
}

/**
 * Enclosed gaps in the board, as clockwise loops.
 *
 * This — not "no moves anywhere" — is what failure looks like. On an open board
 * the frontier always has room somewhere, so play never simply runs out. What
 * goes wrong is *local*: you box in a pocket the wrong shape for a hat, and no
 * placement will ever fill it. That is the failure scene 3 wants a reader to
 * walk into, and it is visible on screen rather than abstract.
 *
 * Outer boundaries wind counter-clockwise, so holes are the negatively-signed
 * loops.
 */
export function holes(board: Board): Eis[][] {
  return boundaryLoops(board.tiles).filter((loop) => signedArea2(loop) < 0);
}

/**
 * Holes no legal placement can begin to fill — the board is stuck there.
 *
 * A hole with no move along any of its steps can only grow more stuck, since
 * nothing outside it can reach in.
 */
export function deadHoles(board: Board): Eis[][] {
  const trapped: Eis[][] = [];
  for (const hole of holes(board)) {
    const points = new Set(hole.map((p) => `${p.a},${p.b}`));
    const steps = frontier(board).filter(
      (s) => points.has(`${s.from.a},${s.from.b}`) && points.has(`${s.to.a},${s.to.b}`),
    );
    if (steps.every((s) => movesAlongStep(board, s).length === 0)) trapped.push(hole);
  }
  return trapped;
}

/** Does this placement close a hole — i.e. leave no free space around it? */
export function touchesOnlyAtPoint(board: Board, iso: Isometry): boolean {
  // A placement that shares no lattice *step* with the frontier is touching at
  // a point at most. Kept as a predicate rather than a filter so callers can
  // decide; `movesAlongStep` never produces one.
  const steps = new Set(frontier(board).map((s) => `${s.from.a},${s.from.b}`));
  return !HAT_STEPS.some((h) => {
    const p = add(iso.t, linear(h.from, iso.rot, iso.reflected));
    return steps.has(`${p.a},${p.b}`);
  });
}
